baseURL = "https://xin-owo.github.io"
title = 'My New Hugo Site'
theme = 'PaperMod'
langusgeCode = "zh-tw"
buildDrafts = false

[[menu.main]]
 
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 10

[[menu.main]]
 
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 20
	
[[menu.main]]
 
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 30